version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command:  /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd -data-path=/data
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4151"
      - "4150:4150"
    volumes:
      - nsqd:/data
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis:/data
  elasticsearch:
    image: elasticsearch:8.6.2
    ports:
      - "9200:9200"
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/data
volumes:
  nsqd:
    driver: local
  redis:
    driver: local
  elasticsearch:
    driver: local